#!/bin/bash
echo $(pwd)
docker container run \
-it \
--rm \
--name=tf-spiking-dash \
-v "$(pwd)":/visualizer \
-v "$(pwd)"/../spiking-model-configuration/configuration/:/app/src/configfiles \
-v "$(pwd)"/../spiking-model-configuration/src/:/app/src/configuration \
-v /media/internal/record/tfspikingnn:/record \
-p 8050:8050 \
louisross/tf-spiking-dash:1.0 \
bash
